export const SIGN_IN_REQUESTED = 'SIGN_IN_REQUESTED';
export const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';

export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED';
export const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED';

export const GET_CURRENT_USER_REQUESTED = 'GET_CURRENT_USER_REQUESTED';
export const GET_CURRENT_USER_SUCCEEDED = 'GET_CURRENT_USER_SUCCEEDED';

export const SIGN_OUT_REQUESTED = 'SIGN_OUT_REQUESTED';
export const SIGN_OUT_SUCCEEDED = 'SIGN_OUT_SUCCEEDED';
