export const GET_ALL_FILES_REQUESTED = 'GET_ALL_FILES_REQUESTED';
export const GET_ALL_FILES_SUCCEEDED = 'GET_ALL_FILES_SUCCEEDED';

export const UPLOAD_FILES_REQUESTED = 'UPLOAD_FILES_REQUESTED';
export const UPLOAD_FILES_SUCCEEDED = 'UPLOAD_FILES_SUCCEEDED';

export const DELETE_FILE_REQUESTED = 'DELETE_FILE_REQUESTED';
export const DELETE_FILE_SUCCEEDED = 'DELETE_FILE_SUCCEEDED';
